import { supabase } from "@/integrations/supabase/client";

export interface StoryRequest {
  age: number;
  personality: string;
  interests: string[];
  dislikes?: string;
  category?: 'bedtime' | 'ABCs' | 'math' | 'science' | 'adventure';
}

export interface GeneratedStory {
  title: string;
  content: string;
  ssmlContent: string;
  category: string;
  duration: number;
}

export class StoryGenerator {
  private static async generateStoryWithAI(request: StoryRequest): Promise<GeneratedStory> {
    const { age, personality, interests, dislikes, category } = request;
    
    // Create a detailed prompt for longer, structured stories
    const prompt = `Create a complete children's story for a ${age}-year-old child with these characteristics:

CHILD PROFILE:
- Age: ${age} years old
- Personality: ${personality}
- Interests: ${interests.join(', ')}
${dislikes ? `- Dislikes: ${dislikes}` : ''}
- Story Category: ${category || 'adventure'}

STORY REQUIREMENTS:
- Length: 400-600 words (5-7 minute reading time)
- Structure: Clear beginning, middle, and end
- Beginning: Introduce the main character and setting
- Middle: Create an engaging adventure or challenge
- End: Resolve the story with a positive lesson

CONTENT GUIDELINES:
- Use vocabulary appropriate for a ${age}-year-old
- Include the child's interests: ${interests.join(', ')}
- Match their ${personality} personality
${dislikes ? `- Avoid mentioning: ${dislikes}` : ''}
- Include dialogue and descriptive scenes
- Create memorable characters
- End with a meaningful lesson about friendship, kindness, courage, or learning

STORY ELEMENTS TO INCLUDE:
- Vivid descriptions of settings
- Character emotions and growth
- A clear problem and solution
- Exciting but age-appropriate action
- A satisfying, complete ending

Please write a complete story that feels like a real children's book - with a proper beginning that sets the scene, a middle that builds excitement, and an ending that brings everything together beautifully.

Format your response as:
TITLE: [Creative Story Title]
STORY: [Complete Story Content]
SSML: [Story Content with SSML markup for expressive reading]`;

    try {
      console.log('Calling AI story generation with enhanced prompt for longer stories');
      
      const { data, error } = await supabase.functions.invoke('generate-story-ai', {
        body: { prompt }
      });

      if (error) {
        console.error('AI story generation error:', error);
        throw new Error(`AI generation failed: ${error.message}`);
      }

      if (!data || !data.generatedText) {
        console.error('No generated text received from AI');
        throw new Error('No story content generated by AI. Please check your OpenAI API key configuration.');
      }

      // Parse the AI response
      const response = data.generatedText;
      console.log('AI generated response length:', response.length);
      
      const titleMatch = response.match(/TITLE:\s*(.*?)(?:\n|STORY:)/i);
      const storyMatch = response.match(/STORY:\s*(.*?)(?:\n|SSML:)/is);
      const ssmlMatch = response.match(/SSML:\s*([\s\S]*)/i);

      const title = titleMatch ? titleMatch[1].trim() : `The ${personality.charAt(0).toUpperCase() + personality.slice(1)} Adventure`;
      let content = storyMatch ? storyMatch[1].trim() : '';
      let ssmlContent = ssmlMatch ? ssmlMatch[1].trim() : '';
      
      // If we don't have separate content, extract clean text from the response
      if (!content && !ssmlContent) {
        content = response.replace(/^TITLE:\s*.*?\n/i, '').trim();
        ssmlContent = content;
      } else if (!content && ssmlContent) {
        content = ssmlContent.replace(/<[^>]*>/g, '').replace(/\s+/g, ' ').trim();
      } else if (content && !ssmlContent) {
        ssmlContent = content;
      }

      // Ensure we have valid content
      if (!content || content.length < 200) {
        throw new Error('Generated story content is too short. Please try again.');
      }

      // Estimate duration based on word count (longer stories now)
      const wordCount = content.split(/\s+/).length;
      const duration = Math.max(300, Math.min(450, wordCount * 0.7)); // 0.7 seconds per word for longer stories

      console.log('Successfully generated AI story:', { title, wordCount, duration });

      return {
        title,
        content,
        ssmlContent,
        category: category || 'adventure',
        duration: Math.round(duration)
      };
    } catch (error) {
      console.error('Error calling AI story generation:', error);
      throw new Error(`Story generation failed: ${error.message}. Please ensure your OpenAI API key is configured correctly.`);
    }
  }

  static async generateStory(profileId: string, category?: string): Promise<string | null> {
    try {
      // Get the child profile
      let profile;
      if (profileId === 'demo-profile') {
        // Get from localStorage for demo
        const stored = localStorage.getItem('childProfile');
        profile = stored ? JSON.parse(stored) : null;
      } else {
        const { data, error } = await supabase
          .from('child_profiles')
          .select('*')
          .eq('id', profileId)
          .single();
        
        if (error) throw error;
        profile = data;
      }

      if (!profile) throw new Error('Profile not found');

      // Generate story content using AI - no fallbacks, AI is required
      const storyRequest: StoryRequest = {
        age: profile.age,
        personality: profile.personality,
        interests: profile.interests,
        dislikes: profile.dislikes,
        category: category as any || 'adventure'
      };

      console.log('Generating AI story with request:', storyRequest);
      const generatedStory = await this.generateStoryWithAI(storyRequest);
      console.log('Generated story:', generatedStory);

      // Save story to database (skip for demo profile)
      if (profileId !== 'demo-profile') {
        const { data: storyData, error: storyError } = await supabase
          .from('stories')
          .insert({
            child_profile_id: profileId,
            title: generatedStory.title,
            content: generatedStory.content,
            category: generatedStory.category,
            duration: generatedStory.duration
          })
          .select()
          .single();

        if (storyError) throw storyError;
        return storyData.id;
      } else {
        // Store in localStorage for demo
        const demoStory = {
          id: 'demo-story-' + Date.now(),
          ...generatedStory,
          child_profile_id: profileId
        };
        localStorage.setItem('currentStory', JSON.stringify(demoStory));
        return demoStory.id;
      }
    } catch (error) {
      console.error('Error generating story:', error);
      throw error; // Re-throw so the UI can show the actual error
    }
  }

  static async getStory(storyId: string) {
    if (storyId.startsWith('demo-story-')) {
      // Get from localStorage for demo
      const stored = localStorage.getItem('currentStory');
      return stored ? JSON.parse(stored) : null;
    }

    const { data, error } = await supabase
      .from('stories')
      .select('*')
      .eq('id', storyId)
      .single();
    
    if (error) throw error;
    return data;
  }
}
