
interface StoryInfoProps {
  category: string
}

const StoryInfo = ({ category }: StoryInfoProps) => {
  return (
    <div className="mt-8 grid grid-cols-1 md:grid-cols-3 gap-4">
      <div className="bg-kidBlue/20 rounded-2xl p-4 text-center">
        <div className="text-2xl mb-2">⏱️</div>
        <div className="font-fredoka text-gray-700">Duration</div>
        <div className="font-fredoka font-bold text-gray-800">2 min</div>
      </div>
      
      <div className="bg-kidGreen/20 rounded-2xl p-4 text-center">
        <div className="text-2xl mb-2">📚</div>
        <div className="font-fredoka text-gray-700">Category</div>
        <div className="font-fredoka font-bold text-gray-800 capitalize">{category}</div>
      </div>
      
      <div className="bg-kidYellow/20 rounded-2xl p-4 text-center">
        <div className="text-2xl mb-2">🤖</div>
        <div className="font-fredoka text-gray-700">Generated by</div>
        <div className="font-fredoka font-bold text-gray-800">AI</div>
      </div>
    </div>
  )
}

export default StoryInfo
