// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ewkritqwrhqbitotdhio.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV3a3JpdHF3cmhxYml0b3RkaGlvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgwNjk5MzcsImV4cCI6MjA2MzY0NTkzN30.mDm-qgqxvSWBx8BhsMBxcaGQgSpc9O4ZEYuArETSHk8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);